"""create CareerPilot schema tables

Revision ID: 3851b09d1b8b
Revises: 
Create Date: 2026-10-05 20:18:47.422959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3851b09d1b8b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraping_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_url', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('max_concurrency', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('successful_items', sa.Integer(), nullable=False),
    sa.Column('failed_items', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('selectors', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='careerpilot'
    )
    op.create_index(op.f('ix_careerpilot_scraping_jobs_id'), 'scraping_jobs', ['id'], unique=False, schema='careerpilot')
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='careerpilot'
    )
    op.create_index(op.f('ix_careerpilot_users_email'), 'users', ['email'], unique=True, schema='careerpilot')
    op.create_table('resumes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=1000), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['careerpilot.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='careerpilot'
    )
    op.create_index(op.f('ix_careerpilot_resumes_user_id'), 'resumes', ['user_id'], unique=False, schema='careerpilot')
    op.create_table('scraping_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['careerpilot.scraping_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='careerpilot'
    )
    op.create_index(op.f('ix_careerpilot_scraping_records_id'), 'scraping_records', ['id'], unique=False, schema='careerpilot')
    op.create_index(op.f('ix_careerpilot_scraping_records_job_id'), 'scraping_records', ['job_id'], unique=False, schema='careerpilot')
    op.create_table('scraping_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['careerpilot.scraping_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='careerpilot'
    )
    op.create_index(op.f('ix_careerpilot_scraping_targets_id'), 'scraping_targets', ['id'], unique=False, schema='careerpilot')
    op.create_index(op.f('ix_careerpilot_scraping_targets_job_id'), 'scraping_targets', ['job_id'], unique=False, schema='careerpilot')
    op.create_table('ats_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('matched_keywords', sa.Text(), nullable=False),
    sa.Column('missing_keywords', sa.Text(), nullable=False),
    sa.Column('recommendations', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['careerpilot.resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['careerpilot.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='careerpilot'
    )
    op.create_index(op.f('ix_careerpilot_ats_reports_resume_id'), 'ats_reports', ['resume_id'], unique=False, schema='careerpilot')
    op.create_index(op.f('ix_careerpilot_ats_reports_user_id'), 'ats_reports', ['user_id'], unique=False, schema='careerpilot')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_careerpilot_ats_reports_user_id'), table_name='ats_reports', schema='careerpilot')
    op.drop_index(
    op.f('ix_careerpilot_ats_reports_user_id'),
    table_name='ats_reports',
    schema='careerpilot',
)
    op.drop_index(
    op.f('ix_careerpilot_ats_reports_resume_id'),
    table_name='ats_reports',
    schema='careerpilot',)
    op.drop_table('ats_reports', schema='careerpilot')
    op.drop_index(op.f('ix_careerpilot_scraping_targets_job_id'), table_name='scraping_targets', schema='careerpilot')
    op.drop_index(op.f('ix_careerpilot_scraping_targets_id'), table_name='scraping_targets', schema='careerpilot')
    op.drop_table('scraping_targets', schema='careerpilot')
    op.drop_index(op.f('ix_careerpilot_scraping_records_job_id'), table_name='scraping_records', schema='careerpilot')
    op.drop_index(op.f('ix_careerpilot_scraping_records_id'), table_name='scraping_records', schema='careerpilot')
    op.drop_table('scraping_records', schema='careerpilot')
    op.drop_index(op.f('ix_careerpilot_resumes_user_id'), table_name='resumes', schema='careerpilot')
    op.drop_table('resumes', schema='careerpilot')
    op.drop_index(op.f('ix_careerpilot_users_email'), table_name='users', schema='careerpilot')
    op.drop_table('users', schema='careerpilot')
    op.drop_index(op.f('ix_careerpilot_scraping_jobs_id'), table_name='scraping_jobs', schema='careerpilot')
    op.drop_table('scraping_jobs', schema='careerpilot')
    # ### end Alembic commands ###
