import type {
  Resume,
  ATSAnalysis,
  JobPosting,
  Application,
  Company,
  ProfileOptimization,
  DashboardStats,
  ResumeContent,
} from '@/lib/types';

export const DEMO_MODE = true;

export const demoResumeContent: ResumeContent = {
  personalInfo: {
    fullName: 'Alex Morgan',
    email: 'alex.morgan@email.com',
    phone: '+1 (555) 123-4567',
    location: 'San Francisco, CA',
    website: 'alexmorgan.dev',
    linkedin: 'linkedin.com/in/alexmorgan',
    github: 'github.com/alexmorgan',
    title: 'Senior Frontend Engineer',
  },
  summary:
    'Senior Frontend Engineer with 7+ years of experience building performant web applications using React, TypeScript, and Next.js. Passionate about accessibility, design systems, and developer experience. Led teams to ship products serving millions of users.',
  workExperience: [
    {
      id: 'we1',
      company: 'TechCorp Inc.',
      position: 'Senior Frontend Engineer',
      location: 'San Francisco, CA',
      startDate: '2021-03',
      endDate: '',
      current: true,
      description:
        'Lead frontend development for a B2B analytics platform serving 2M+ monthly users. Architected a design system used across 12 product teams. Improved Core Web Vitals by 40% and reduced bundle size by 35%.',
    },
    {
      id: 'we2',
      company: 'StartupHub',
      position: 'Frontend Engineer',
      location: 'Remote',
      startDate: '2018-06',
      endDate: '2021-02',
      current: false,
      description:
        'Built the customer-facing dashboard from scratch using React and Redux. Implemented real-time data visualization with D3.js. Collaborated with design to create a cohesive component library.',
    },
  ],
  education: [
    {
      id: 'ed1',
      institution: 'University of California, Berkeley',
      degree: 'B.S. Computer Science',
      field: 'Computer Science',
      startDate: '2014-09',
      endDate: '2018-05',
      gpa: '3.8',
    },
  ],
  skills: [
    { id: 's1', name: 'React', level: 'expert' },
    { id: 's2', name: 'TypeScript', level: 'expert' },
    { id: 's3', name: 'Next.js', level: 'advanced' },
    { id: 's4', name: 'Tailwind CSS', level: 'advanced' },
    { id: 's5', name: 'Node.js', level: 'advanced' },
    { id: 's6', name: 'GraphQL', level: 'intermediate' },
    { id: 's7', name: 'Jest', level: 'intermediate' },
    { id: 's8', name: 'Accessibility', level: 'advanced' },
  ],
  projects: [
    {
      id: 'p1',
      name: 'OpenSource Design System',
      description: 'A React component library with 50+ accessible components, 3.2k GitHub stars.',
      technologies: ['React', 'TypeScript', 'Radix UI', 'Tailwind CSS'],
      url: 'github.com/alexmorgan/design-system',
    },
  ],
  certifications: [
    {
      id: 'c1',
      name: 'AWS Certified Developer - Associate',
      issuer: 'Amazon Web Services',
      date: '2023-01',
    },
  ],
  achievements: [
    'Speaker at ReactConf 2023 — "Building Accessible Design Systems"',
    'Reduced page load time by 60% across the analytics platform',
    'Mentored 5 junior engineers, 3 promoted to mid-level',
  ],
  languages: [
    { id: 'l1', name: 'English', proficiency: 'native' },
    { id: 'l2', name: 'Spanish', proficiency: 'conversational' },
  ],
  volunteer: ['Code coach at local bootcamp, teaching web fundamentals to career switchers'],
  customSections: [],
};

export const demoResumes: Resume[] = [
  {
    id: 'demo-resume-1',
    user_id: 'demo-user',
    title: 'Senior Frontend Engineer Resume',
    template: 'modern-professional',
    content: demoResumeContent,
    ats_score: 87,
    status: 'published',
    created_at: '2024-08-15T10:00:00Z',
    updated_at: '2024-09-01T14:00:00Z',
  },
  {
    id: 'demo-resume-2',
    user_id: 'demo-user',
    title: 'Full-Stack Developer Resume',
    template: 'software-engineer',
    content: {
      ...demoResumeContent,
      personalInfo: { ...demoResumeContent.personalInfo, title: 'Full-Stack Developer' },
      skills: [
        ...demoResumeContent.skills,
        { id: 's9', name: 'PostgreSQL', level: 'advanced' },
        { id: 's10', name: 'Docker', level: 'intermediate' },
      ],
    },
    ats_score: 72,
    status: 'draft',
    created_at: '2024-07-20T10:00:00Z',
    updated_at: '2024-08-28T14:00:00Z',
  },
];

export const demoATSAnalyses: ATSAnalysis[] = [
  {
    id: 'demo-ats-1',
    user_id: 'demo-user',
    resume_id: 'demo-resume-1',
    job_title: 'Senior Frontend Engineer',
    company_name: 'Airbnb',
    job_description:
      'We are looking for a Senior Frontend Engineer to build accessible, performant web applications using React and TypeScript.',
    overall_score: 82,
    keyword_match_score: 78,
    skills_match_score: 85,
    experience_alignment_score: 80,
    formatting_score: 95,
    matching_keywords: ['React', 'TypeScript', 'Next.js', 'Accessibility', 'CSS'],
    missing_keywords: ['Jest', 'Testing Library', 'CI/CD', 'Webpack'],
    recommendations: [
      'Add measurable achievements with specific metrics',
      'Include experience with testing frameworks like Jest',
      'Mention CI/CD pipeline experience',
      'Highlight performance optimization work with quantified results',
    ],
    created_at: '2024-09-01T14:00:00Z',
  },
  {
    id: 'demo-ats-2',
    user_id: 'demo-user',
    resume_id: 'demo-resume-2',
    job_title: 'Full-Stack Engineer',
    company_name: 'Stripe',
    job_description:
      'Seeking a Full-Stack Engineer proficient in React, Node.js, and PostgreSQL to build payment infrastructure.',
    overall_score: 74,
    keyword_match_score: 70,
    skills_match_score: 80,
    experience_alignment_score: 72,
    formatting_score: 90,
    matching_keywords: ['React', 'Node.js', 'PostgreSQL', 'TypeScript'],
    missing_keywords: ['Kubernetes', 'Microservices', 'GraphQL', 'Redis'],
    recommendations: [
      'Add backend architecture experience details',
      'Mention experience with microservices if applicable',
      'Include any infrastructure or DevOps work',
    ],
    created_at: '2024-08-28T14:00:00Z',
  },
];

export const demoJobs: JobPosting[] = [
  {
    id: 'job-1',
    title: 'Senior Frontend Engineer',
    company: 'Airbnb',
    companyLogo: '',
    location: 'San Francisco, CA',
    country: 'United States',
    city: 'San Francisco',
    workMode: 'hybrid',
    employmentType: 'full-time',
    experienceLevel: 'senior',
    postedAt: '2024-09-09T08:00:00Z',
    sourceName: 'Airbnb Careers',
    sourceUrl: 'https://careers.airbnb.com',
    salaryMin: 160000,
    salaryMax: 220000,
    salaryCurrency: 'USD',
    skills: ['React', 'TypeScript', 'Next.js', 'Accessibility', 'CSS', 'Jest', 'CI/CD'],
    description:
      'We are looking for a Senior Frontend Engineer to join our Host Platform team. You will build accessible, performant web applications that help hosts manage their listings and grow their business.',
    responsibilities: [
      'Build and maintain frontend features for the Host Platform',
      'Collaborate with designers to implement accessible UI components',
      'Optimize application performance and Core Web Vitals',
      'Mentor junior engineers and conduct code reviews',
      'Work with product managers to define technical requirements',
    ],
    requirements: [
      '5+ years of frontend engineering experience',
      'Expert knowledge of React and TypeScript',
      'Experience with Next.js or similar SSR frameworks',
      'Strong understanding of web accessibility (WCAG)',
      'Experience with testing frameworks (Jest, Testing Library)',
    ],
    benefits: [
      'Competitive salary and equity',
      'Comprehensive health, dental, and vision insurance',
      '401(k) with company match',
      'Annual learning and development stipend',
      'Flexible PTO',
    ],
    matchScore: 88,
    matchingSkills: ['React', 'TypeScript', 'Next.js', 'Accessibility', 'CSS'],
    missingSkills: ['Jest', 'CI/CD'],
  },
  {
    id: 'job-2',
    title: 'Full-Stack Engineer',
    company: 'Stripe',
    companyLogo: '',
    location: 'Remote',
    country: 'United States',
    city: 'Remote',
    workMode: 'remote',
    employmentType: 'full-time',
    experienceLevel: 'mid',
    postedAt: '2024-09-10T06:00:00Z',
    sourceName: 'Stripe Careers',
    sourceUrl: 'https://stripe.com/jobs',
    salaryMin: 140000,
    salaryMax: 200000,
    salaryCurrency: 'USD',
    skills: ['React', 'Node.js', 'PostgreSQL', 'TypeScript', 'Kubernetes', 'GraphQL'],
    description:
      'Join the Payments Infrastructure team at Stripe. Build scalable backend services and customer-facing dashboards for the worlds leading payment platform.',
    responsibilities: [
      'Design and build full-stack features for payment dashboards',
      'Write clean, tested, and maintainable code',
      'Participate in on-call rotation',
      'Collaborate across teams to ship integrated features',
    ],
    requirements: [
      '3+ years of full-stack engineering experience',
      'Proficiency in React and Node.js',
      'Experience with PostgreSQL and database design',
      'Understanding of distributed systems',
    ],
    benefits: [
      'Remote-first culture',
      'Top-tier compensation',
      'Health and wellness benefits',
      'Home office stipend',
    ],
    matchScore: 76,
    matchingSkills: ['React', 'Node.js', 'PostgreSQL', 'TypeScript'],
    missingSkills: ['Kubernetes', 'GraphQL'],
  },
  {
    id: 'job-3',
    title: 'Frontend Developer',
    company: 'Shopify',
    companyLogo: '',
    location: 'Ottawa, Canada',
    country: 'Canada',
    city: 'Ottawa',
    workMode: 'hybrid',
    employmentType: 'full-time',
    experienceLevel: 'mid',
    postedAt: '2024-09-08T10:00:00Z',
    sourceName: 'Shopify Careers',
    sourceUrl: 'https://www.shopify.com/careers',
    salaryMin: 90000,
    salaryMax: 130000,
    salaryCurrency: 'CAD',
    skills: ['React', 'TypeScript', 'GraphQL', 'CSS', 'Accessibility'],
    description:
      'Build merchant-facing tools that empower entrepreneurs worldwide. Work on Polaris, our design system, and merchant dashboard features.',
    responsibilities: [
      'Develop merchant-facing React applications',
      'Contribute to the Polaris design system',
      'Ensure accessibility compliance across products',
      'Collaborate with UX designers and product managers',
    ],
    requirements: [
      '3+ years frontend development experience',
      'Strong React and TypeScript skills',
      'Experience with GraphQL APIs',
      'Passion for accessibility and inclusive design',
    ],
    benefits: [
      'Flexible work arrangements',
      'Health benefits',
      'Professional development budget',
      'Equity grants',
    ],
    matchScore: 84,
    matchingSkills: ['React', 'TypeScript', 'CSS', 'Accessibility'],
    missingSkills: ['GraphQL'],
  },
  {
    id: 'job-4',
    title: 'Lead Software Engineer',
    company: 'Vercel',
    companyLogo: '',
    location: 'Remote',
    country: 'United States',
    city: 'Remote',
    workMode: 'remote',
    employmentType: 'full-time',
    experienceLevel: 'lead',
    postedAt: '2024-09-10T03:00:00Z',
    sourceName: 'Vercel Careers',
    sourceUrl: 'https://vercel.com/careers',
    salaryMin: 180000,
    salaryMax: 260000,
    salaryCurrency: 'USD',
    skills: ['Next.js', 'React', 'TypeScript', 'Node.js', 'Edge Computing', 'Webpack'],
    description:
      'Lead the development of Next.js features and the Vercel dashboard. Shape the future of web development tooling.',
    responsibilities: [
      'Architect and lead development of core platform features',
      'Set technical direction for the frontend engineering team',
      'Review and approve architectural decisions',
      'Represent Vercel in the open-source community',
    ],
    requirements: [
      '8+ years of software engineering experience',
      'Deep expertise in React and Next.js',
      'Experience leading engineering teams',
      'Open-source contributions preferred',
    ],
    benefits: [
      'Fully remote',
      'Competitive equity',
      'Health, dental, vision',
      'Unlimited PTO',
    ],
    matchScore: 91,
    matchingSkills: ['Next.js', 'React', 'TypeScript', 'Node.js'],
    missingSkills: ['Edge Computing', 'Webpack'],
  },
  {
    id: 'job-5',
    title: 'UI Engineer',
    company: 'Figma',
    companyLogo: '',
    location: 'San Francisco, CA',
    country: 'United States',
    city: 'San Francisco',
    workMode: 'hybrid',
    employmentType: 'full-time',
    experienceLevel: 'senior',
    postedAt: '2024-09-09T12:00:00Z',
    sourceName: 'Figma Careers',
    sourceUrl: 'https://www.figma.com/careers',
    salaryMin: 150000,
    salaryMax: 210000,
    salaryCurrency: 'USD',
    skills: ['React', 'TypeScript', 'Canvas API', 'WebGL', 'CSS', 'Design Systems'],
    description:
      'Build the future of design tools. Create performant, delightful UI for millions of designers and teams using Figma.',
    responsibilities: [
      'Build complex, interactive UI features in Figma',
      'Optimize rendering performance for large documents',
      'Contribute to Figma component library',
      'Work closely with designers on product UX',
    ],
    requirements: [
      '5+ years frontend experience',
      'Expert in React and TypeScript',
      'Experience with Canvas/WebGL a plus',
      'Passion for design tools and creative software',
    ],
    benefits: [
      'Equity package',
      'Health benefits',
      'Design tool stipend',
      'Wellness reimbursement',
    ],
    matchScore: 79,
    matchingSkills: ['React', 'TypeScript', 'CSS'],
    missingSkills: ['Canvas API', 'WebGL', 'Design Systems'],
  },
  {
    id: 'job-6',
    title: 'React Native Developer',
    company: 'Discord',
    companyLogo: '',
    location: 'San Francisco, CA',
    country: 'United States',
    city: 'San Francisco',
    workMode: 'onsite',
    employmentType: 'full-time',
    experienceLevel: 'mid',
    postedAt: '2024-09-07T14:00:00Z',
    sourceName: 'Discord Careers',
    sourceUrl: 'https://discord.com/jobs',
    salaryMin: 130000,
    salaryMax: 180000,
    salaryCurrency: 'USD',
    skills: ['React Native', 'TypeScript', 'Redux', 'iOS', 'Android', 'GraphQL'],
    description:
      'Build the Discord mobile experience for hundreds of millions of users. Work on real-time messaging, voice, and video features.',
    responsibilities: [
      'Develop and maintain React Native mobile features',
      'Optimize app performance for low-end devices',
      'Collaborate with backend on real-time features',
      'Implement pixel-perfect UI from designs',
    ],
    requirements: [
      '3+ years React Native experience',
      'Strong TypeScript skills',
      'Published mobile apps on App Store or Play Store',
      'Experience with real-time applications',
    ],
    benefits: [
      'Gaming-focused culture',
      'Comprehensive health benefits',
      'Commuter benefits',
      'Snacks and meals',
    ],
    matchScore: 62,
    matchingSkills: ['TypeScript', 'Redux'],
    missingSkills: ['React Native', 'iOS', 'Android', 'GraphQL'],
  },
];

export const demoApplications: Application[] = [
  {
    id: 'app-1',
    user_id: 'demo-user',
    job_id: 'job-1',
    job_data: demoJobs[0],
    resume_id: 'demo-resume-1',
    cover_letter: 'Dear Hiring Manager, I am excited to apply for the Senior Frontend Engineer position at Airbnb...',
    status: 'interview',
    notes: 'First round technical interview scheduled for next week.',
    source_url: 'https://careers.airbnb.com',
    applied_at: '2024-09-02T10:00:00Z',
    created_at: '2024-09-01T10:00:00Z',
    updated_at: '2024-09-05T14:00:00Z',
  },
  {
    id: 'app-2',
    user_id: 'demo-user',
    job_id: 'job-2',
    job_data: demoJobs[1],
    resume_id: 'demo-resume-2',
    cover_letter: null,
    status: 'applied',
    notes: '',
    source_url: 'https://stripe.com/jobs',
    applied_at: '2024-09-04T10:00:00Z',
    created_at: '2024-09-03T10:00:00Z',
    updated_at: '2024-09-04T10:00:00Z',
  },
  {
    id: 'app-3',
    user_id: 'demo-user',
    job_id: 'job-3',
    job_data: demoJobs[2],
    resume_id: 'demo-resume-1',
    cover_letter: null,
    status: 'preparing',
    notes: 'Need to tailor resume for GraphQL experience.',
    source_url: null,
    applied_at: null,
    created_at: '2024-09-08T10:00:00Z',
    updated_at: '2024-09-08T10:00:00Z',
  },
  {
    id: 'app-4',
    user_id: 'demo-user',
    job_id: 'job-4',
    job_data: demoJobs[3],
    resume_id: 'demo-resume-1',
    cover_letter: null,
    status: 'screening',
    notes: 'Recruiter call completed, waiting for next steps.',
    source_url: 'https://vercel.com/careers',
    applied_at: '2024-09-05T10:00:00Z',
    created_at: '2024-09-04T10:00:00Z',
    updated_at: '2024-09-06T14:00:00Z',
  },
  {
    id: 'app-5',
    user_id: 'demo-user',
    job_id: 'job-5',
    job_data: demoJobs[4],
    resume_id: null,
    cover_letter: null,
    status: 'saved',
    notes: '',
    source_url: null,
    applied_at: null,
    created_at: '2024-09-09T10:00:00Z',
    updated_at: '2024-09-09T10:00:00Z',
  },
];

export const demoCompanies: Company[] = [
  {
    id: 'company-1',
    name: 'Airbnb',
    website: 'airbnb.com',
    industry: 'Travel & Hospitality',
    location: 'San Francisco, CA',
    description:
      'Airbnb is a community marketplace for people to list, discover, and book unique accommodations around the world.',
    employeeCount: '5,000-10,000',
    openJobs: 42,
    leadership: [
      { name: 'Brian Chesky', role: 'CEO & Co-founder', profileUrl: 'linkedin.com/in/brianchesky' },
      { name: 'Joe Gebbia', role: 'Co-founder', profileUrl: 'linkedin.com/in/joegebbia' },
    ],
    referralContacts: [
      {
        id: 'ref-1',
        name: 'Sarah Chen',
        role: 'Senior Engineering Manager',
        company: 'Airbnb',
        profileUrl: 'linkedin.com/in/sarahchen',
        relevance: 'Manages the Host Platform frontend team',
        connectionStatus: 'none',
      },
      {
        id: 'ref-2',
        name: 'Marcus Johnson',
        role: 'Frontend Engineer',
        company: 'Airbnb',
        profileUrl: 'linkedin.com/in/marcusjohnson',
        relevance: 'Works on the team hiring for this role',
        connectionStatus: 'connected',
      },
      {
        id: 'ref-3',
        name: 'Priya Patel',
        role: 'Technical Recruiter',
        company: 'Airbnb',
        profileUrl: 'linkedin.com/in/priyapatel',
        relevance: 'Recruits for engineering roles',
        connectionStatus: 'none',
      },
    ],
  },
  {
    id: 'company-2',
    name: 'Stripe',
    website: 'stripe.com',
    industry: 'Financial Technology',
    location: 'Remote / South San Francisco, CA',
    description:
      'Stripe is a technology company that builds economic infrastructure for the internet. Businesses of every size use Stripe to accept payments and manage their businesses online.',
    employeeCount: '5,000-10,000',
    openJobs: 68,
    leadership: [
      { name: 'Patrick Collison', role: 'CEO & Co-founder', profileUrl: 'linkedin.com/in/patrickcollison' },
      { name: 'John Collison', role: 'Co-founder & President', profileUrl: 'linkedin.com/in/johncollison' },
    ],
    referralContacts: [
      {
        id: 'ref-4',
        name: 'David Kim',
        role: 'Engineering Manager',
        company: 'Stripe',
        profileUrl: 'linkedin.com/in/davidkim',
        relevance: 'Leads the Payments Infrastructure team',
        connectionStatus: 'none',
      },
      {
        id: 'ref-5',
        name: 'Emily Rodriguez',
        role: 'Senior Recruiter',
        company: 'Stripe',
        profileUrl: 'linkedin.com/in/emilyrodriguez',
        relevance: 'Hires for full-stack engineering roles',
        connectionStatus: 'none',
      },
    ],
  },
];

export const demoProfileOptimizations: ProfileOptimization[] = [
  {
    id: 'prof-1',
    user_id: 'demo-user',
    platform: 'linkedin',
    current_headline: 'Frontend Developer',
    suggested_headline: 'Senior Frontend Engineer | React, Next.js, TypeScript | Building AI-Powered Web Applications',
    current_summary: 'I am a frontend developer with experience in React.',
    suggested_summary:
      'Senior Frontend Engineer with 7+ years building performant, accessible web applications used by millions. Expert in React, TypeScript, and Next.js. Passionate about design systems, developer experience, and mentoring teams. Currently exploring AI-powered web experiences.',
    suggestions: [
      {
        section: 'Headline',
        current: 'Frontend Developer',
        suggested: 'Senior Frontend Engineer | React, Next.js, TypeScript | Building AI-Powered Web Applications',
        reason: 'Include your seniority, core skills, and a value proposition. Recruiters search for specific technologies.',
      },
      {
        section: 'Summary',
        current: 'I am a frontend developer with experience in React.',
        suggested: 'Senior Frontend Engineer with 7+ years building performant, accessible web applications used by millions. Expert in React, TypeScript, and Next.js.',
        reason: 'Add years of experience, key technologies, and scale of impact. Your current summary is too vague.',
      },
      {
        section: 'Skills',
        current: 'React, JavaScript, HTML, CSS',
        suggested: 'React, TypeScript, Next.js, Tailwind CSS, Node.js, GraphQL, Jest, Accessibility, Web Performance',
        reason: 'Add TypeScript and your full tech stack. Recruiters filter by specific skills.',
      },
    ],
    completeness_score: 65,
    created_at: '2024-09-01T10:00:00Z',
  },
];

export const demoDashboardStats: DashboardStats = {
  totalResumes: 2,
  averageAtsScore: 79,
  savedJobs: 6,
  applicationsSubmitted: 4,
  interviewProgress: 25,
};

export function createEmptyResumeContent(): ResumeContent {
  return {
    personalInfo: {
      fullName: '',
      email: '',
      phone: '',
      location: '',
      website: '',
      linkedin: '',
      github: '',
      title: '',
    },
    summary: '',
    workExperience: [],
    education: [],
    skills: [],
    projects: [],
    certifications: [],
    achievements: [],
    languages: [],
    volunteer: [],
    customSections: [],
  };
}
